// Plan 0058 M1 (Spec 0058 R3, R6; ruling Q8; ADR-0112 D2; J3): the
// atlantis.remote/1 conformance vectors, generated by the C++ implementation
// and committed for every other implementation to check against:
//   - codec_vectors.jsonl: one wire value per line, produced by the C++
//     codec (src/remote/src/codec.h) from a fixed list of values. Another
//     implementation decodes each and re-encodes it to the same bytes.
//   - sdk_transcripts.jsonl: per named scenario, the commands the C++
//     Gameplay SDK submits for it (recorded on an InProcess connection,
//     encoded by the same codec). The C# SDK runs the same scenarios
//     against the fixture server and must submit the same commands (R3).
// A committed file that differs from what the C++ code produces now fails
// here, with the expected text written to the build tree (the Plan 0057 J4
// pattern); nothing rewrites a committed file.

#include "codec.h"

#include "gameplay_fixture.h"

#include <atlantis/gameplay/generated/world.h>
#include <atlantis/gameplay/transaction.h>
#include <atlantis/gameplay/world.h>

#include <atlantis/connection/json.h>
#include <atlantis/remote/session_file.h>
#include <atlantis/world/world_schema.h>

#include <catch2/catch_test_macros.hpp>

#include <array>
#include <bit>
#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iterator>
#include <limits>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace {

namespace fs = std::filesystem;
namespace json = atlantis::connection::json;
namespace codec = atlantis::remote::codec;
namespace access = atlantis::world::access;
namespace connection = atlantis::connection;
namespace gp = atlantis::gameplay;
namespace w = atlantis::gameplay::world;
using atlantis::gameplay::test::GameplayFixture;
using atlantis::gameplay::test::guid;

[[nodiscard]] std::string readBytes(const fs::path& path) {
  std::ifstream in(path, std::ios::binary);
  return std::string((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
}

// Compares with the committed file; on a mismatch writes the expected text to
// the build tree and fails with how to update it.
void checkCurrent(const std::string& expected, std::string_view name) {
  const fs::path committed = fs::path(ATLANTIS_CSHARP_CONFORMANCE_DIR) / std::string(name);
  const std::string actual = readBytes(committed);
  if (actual == expected) {
    SUCCEED();
    return;
  }
  const fs::path dir = fs::path(ATLANTIS_CSHARP_CONFORMANCE_EXPECTED_DIR);
  fs::create_directories(dir);
  const fs::path out = dir / (std::string(name) + ".expected");
  {
    std::ofstream file(out, std::ios::binary | std::ios::trunc);
    file << expected;
  }
  FAIL(committed.generic_string() << " is stale (" << actual.size() << " bytes committed, " << expected.size()
                                  << " generated).\nThe expected text is in " << out.generic_string()
                                  << ".\nRegenerate: run atlantis_csharp_conformance_tests and copy that file over "
                                     "the committed one.");
}

// --- codec_vectors.jsonl --------------------------------------------------------

struct Vector {
  std::string name;
  std::string type;
  json::Value wire;
};

[[nodiscard]] json::Value line(const Vector& vector) {
  json::Value out = json::Value::object();
  out.set("case", json::Value::string(vector.name));
  out.set("type", json::Value::string(vector.type));
  out.set("wire", vector.wire);
  return out;
}

const auto kEntity = guid("58005800-0000-4000-8000-0000000000b1");
const auto kOther = guid("52052052-0002-4052-8052-000000000002");
const auto kAsset = atlantis::asset_system::parseAssetGuid("52052052-00aa-4052-8052-0000000000aa").value();
const auto kLight = atlantis::schema::typeId("world::Light");
const auto kIntensity = atlantis::schema::fieldId("world::Light", "intensity");

[[nodiscard]] std::vector<Vector> codecVectors() {
  std::vector<Vector> out;
  const auto value = [&](std::string name, access::PropertyValue v) {
    // Every vector must round-trip through the C++ codec itself.
    const json::Value wire = codec::encode(v);
    const auto decoded = codec::decodePropertyValue(wire);
    REQUIRE(decoded.has_value());
    REQUIRE(codec::encode(*decoded) == wire);
    out.push_back({"value." + std::move(name), "PropertyValue", wire});
  };
  value("u64.zero", std::uint64_t{0});
  value("u64.one", std::uint64_t{1});
  value("u64.max", std::numeric_limits<std::uint64_t>::max());
  value("f32.zero", 0.0f);
  value("f32.negative_zero", -0.0f);
  value("f32.one", 1.0f);
  value("f32.tenth", 0.1f);
  value("f32.negative", -2.5f);
  value("f32.third", 1.0f / 3.0f);
  value("f32.large", 1e20f);
  value("f32.small", 1e-5f);
  value("f32.fraction", 123456.7f);
  value("f32.integer_large", 16777216.0f);
  value("f32.max", std::numeric_limits<float>::max());
  value("f32.lowest", std::numeric_limits<float>::lowest());
  value("f32.min_normal", std::numeric_limits<float>::min());
  value("f32.nan", std::numeric_limits<float>::quiet_NaN());
  value("f32.inf", std::numeric_limits<float>::infinity());
  value("f32.negative_inf", -std::numeric_limits<float>::infinity());
  value("vec3", std::array<float, 3>{1.0f, 0.6f, 0.2f});
  value("vec3.nan", std::array<float, 3>{std::numeric_limits<float>::quiet_NaN(), 0.0f, -0.0f});
  value("vec4", std::array<float, 4>{1.5f, 2.0f, -1.5f, 1.0f});
  value("asset_guid", kAsset);
  value("asset_guid.nil", atlantis::asset_system::AssetGuid{});
  value("entity_guid", kEntity);
  value("entity_guid.nil", atlantis::asset_system::EntityGuid{});
  value("enum.zero", access::EnumValue{0});
  value("enum.one", access::EnumValue{1});
  value("enum.negative", access::EnumValue{-2});
  value("enum.max", access::EnumValue{std::numeric_limits<std::int64_t>::max()});
  value("enum.min", access::EnumValue{std::numeric_limits<std::int64_t>::min()});
  value("absent", access::Absent{});

  // A sweep of float text: the fixed/scientific boundaries of the shortest
  // form, subnormals, and pseudo-random bit patterns over the whole range
  // (a fixed LCG, so the list never changes). Each must round-trip exactly.
  {
    std::vector<float> floats = {1e-3f,      1e-4f,      1e4f,      1e5f,           123400000.0f, 1234000000.0f,
                                 0.0001234f, 0.00001234f, 1e15f,    1e16f,          1e-10f,       1e10f,
                                 0.5f,       100.0f,      65504.0f, 3.14159274f,    2.71828175f,  1.17549421e-38f,
                                 std::numeric_limits<float>::denorm_min(), -std::numeric_limits<float>::denorm_min()};
    std::uint32_t state = 0x58005800u;
    while (floats.size() < 276) {
      state = state * 1664525u + 1013904223u;
      const float x = std::bit_cast<float>(state);
      if (std::isfinite(x)) floats.push_back(x);
    }
    json::Value wire = json::Value::array();
    for (const float x : floats) {
      const json::Value text = codec::encodeFloat(x);
      const auto back = codec::decodeFloat(text);
      REQUIRE(back.has_value());
      REQUIRE(std::bit_cast<std::uint32_t>(*back) == std::bit_cast<std::uint32_t>(x));
      wire.push(text);
    }
    out.push_back({"float.sweep", "Floats", wire});
  }

  out.push_back({"address", "Address", codec::encode(access::PropertyAddress{kEntity, kLight, kIntensity})});

  const auto command = [&](std::string name, access::Command c) {
    const json::Value wire = codec::encode(c);
    const auto decoded = codec::decodeCommand(wire);
    REQUIRE(decoded.has_value());
    REQUIRE(codec::encode(*decoded) == wire);
    out.push_back({"command." + std::move(name), "Command", wire});
  };
  command("create", access::CreateEntity{kEntity});
  command("destroy", access::DestroyEntity{kEntity});
  command("add", access::AddComponent{kEntity, kLight});
  command("remove", access::RemoveComponent{kEntity, kLight});
  command("set", access::SetProperty{{kEntity, kLight, kIntensity}, 4.0f});
  command("set.nan", access::SetProperty{{kEntity, kLight, kIntensity}, std::numeric_limits<float>::quiet_NaN()});

  const auto event = [&](std::string name, access::Event e) {
    const json::Value wire = codec::encode(e);
    const auto decoded = codec::decodeEvent(wire);
    REQUIRE(decoded.has_value());
    REQUIRE(codec::encode(*decoded) == wire);
    out.push_back({"event." + std::move(name), "Event", wire});
  };
  event("created", access::EntityCreated{kEntity});
  event("destroyed", access::EntityDestroyed{kEntity});
  event("added", access::ComponentAdded{kEntity, kLight});
  event("removed", access::ComponentRemoved{kEntity, kLight});
  event("changed", access::PropertyChanged{{kEntity, kLight, kIntensity}, std::array<float, 3>{0.9f, 0.9f, 0.9f}});

  out.push_back({"failure.non_finite", "Failure",
                 codec::encode(access::CommandFailure{access::CommandTicket{12}, access::AccessError::NonFiniteValue})});
  out.push_back({"failure.light_limit", "Failure",
                 codec::encode(access::CommandFailure{access::CommandTicket{1}, access::AccessError::LightLimitExceeded})});
  out.push_back({"ticket", "TransactionTicket",
                 codec::encode(access::TransactionTicket{access::CommandTicket{7}, 11})});
  out.push_back({"ticket.empty", "TransactionTicket", codec::encode(access::TransactionTicket{})});

  out.push_back({"filter.all", "Filter", codec::encode(connection::EventFilter{})});
  out.push_back({"filter.none", "Filter",
                 codec::encode(connection::EventFilter{connection::EventKindSet(), std::nullopt, std::nullopt})});
  out.push_back({"filter.property", "Filter",
                 codec::encode(connection::EventFilter{
                     connection::EventKindSet::only(connection::EventKind::PropertyChanged), kOther, kLight})});
  out.push_back({"filter.entity", "Filter",
                 codec::encode(connection::EventFilter{connection::EventKindSet::all(), kEntity, std::nullopt})});

  out.push_back({"status", "RuntimeStatus", codec::encode(connection::RuntimeStatus{true, 42, kAsset})});
  out.push_back({"step.plain", "StepRequest", codec::encode(connection::StepRequest{1, std::nullopt})});
  out.push_back({"step.image", "StepRequest",
                 codec::encode(connection::StepRequest{3, std::string("C:\\captures\\beacon \"k\" \xc3\xa9.png")})});
  connection::FrameReport report;
  report.frame = 1234;
  report.applied = true;
  report.data.directionalLights.push_back({{0.5f, -0.75f, 0.25f}, {1.0f, 1.0f, 1.0f}, 3.0f});
  report.data.pointLights.push_back({{1.5f, 2.0f, 1.5f}, {1.0f, 0.6f, 0.2f}, 4.0f, 4.0f});
  for (std::size_t i = 0; i < 16; ++i) {
    report.data.view[i] = static_cast<float>(i) * 0.5f;
    report.data.projection[i] = i % 5 == 0 ? 1.0f : 0.0f;
  }
  report.data.drawItemCount = 7;
  out.push_back({"report.no_image", "FrameReport", codec::encode(report)});
  report.image = connection::CapturedImage{"D:/shots/a b.png", 2374, 1320};
  out.push_back({"report.image", "FrameReport", codec::encode(report)});
  connection::DiagnosticBatch batch;
  batch.entries.push_back({1, connection::DiagnosticSeverity::Warning, "plain"});
  batch.entries.push_back({2, connection::DiagnosticSeverity::Error, "tab\there, quote \" and \x01 control"});
  batch.entries.push_back({3, connection::DiagnosticSeverity::Fatal, "non-ASCII: \xe5\x85\x89"});
  batch.latest = 3;
  batch.dropped = 9;
  out.push_back({"diagnostics", "DiagnosticBatch", codec::encode(batch)});
  out.push_back({"schema.world", "Schema", codec::encodeSchema(atlantis::world::worldSchema())});

  // The session file (session_file.h): its one JSON object.
  atlantis::remote::SessionInfo session;
  session.port = 51234;
  session.token = "00112233445566778899aabbccddeeff";
  session.pid = 4242;
  session.scene = kAsset;
  const std::string text = atlantis::remote::formatSession(session);
  auto parsed = json::parse(text);
  REQUIRE(parsed.isOk());
  out.push_back({"session_file", "SessionFile", parsed.value()});
  return out;
}

[[nodiscard]] std::string codecVectorsText() {
  std::string text;
  for (const Vector& vector : codecVectors()) text += json::write(line(vector)) + "\n";
  return text;
}

// --- sdk_transcripts.jsonl -----------------------------------------------------

// The scenarios: what the C++ Gameplay SDK submits for each, in order. The C#
// SDK's test runs the same-named scenario with the same values (P3).
[[nodiscard]] std::vector<std::pair<std::string, std::function<void(gp::World&)>>> scenarios() {
  const auto beacon = kEntity;
  const auto sun = kOther;
  return {
      {"typed.set.intensity", [=](gp::World& world) { REQUIRE(world.set(sun, w::fields::Light.intensity, 2.5f).isOk()); }},
      {"reflective.set.path", [=](gp::World& world) { REQUIRE(world.set(sun, "Light.intensity", 2.5f).isOk()); }},
      {"typed.add.light",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.create(beacon).add(beacon, w::Light{w::LightKind::Point, {1.0f, 0.6f, 0.2f}, 4.0f, 4.0f});
         REQUIRE(world.submit(tx).isOk());
       }},
      {"typed.spawn.beacon",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.create(beacon)
             .add(beacon, w::Light{w::LightKind::Point, {1.0f, 0.6f, 0.2f}, 4.0f, 4.0f})
             .add(beacon, w::WorldMatrix{{1, 0, 0, 0}, {0, 1, 0, 0}, {0, 0, 1, 0}, {1.5f, 2.0f, 1.5f, 1.0f}});
         REQUIRE(world.submit(tx).isOk());
       }},
      {"typed.move",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.set(beacon, w::fields::WorldMatrix.column3, {0.0f, 2.0f, 1.5f, 1.0f})
             .set(beacon, w::fields::Light.intensity, 6.0f);
         REQUIRE(world.submit(tx).isOk());
       }},
      {"reflective.add.valued",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.add(beacon, "Light", {{"kind", access::EnumValue{1}}, {"intensity", 4.0f}});
         REQUIRE(world.submit(tx).isOk());
       }},
      {"mixed.transaction",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.set(beacon, w::fields::WorldMatrix.column3, {0.0f, 1.0f, 0.0f, 1.0f})
             .set(beacon, "Transform.localScale", std::array<float, 3>{2.0f, 2.0f, 2.0f});
         REQUIRE(world.submit(tx).isOk());
       }},
      {"bare.add.remove.destroy",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.add<w::Light>(beacon).remove<w::WorldMatrix>(beacon).destroy(beacon);
         REQUIRE(world.submit(tx).isOk());
       }},
      {"typed.refused.nan",
       [=](gp::World& world) {
         gp::Transaction tx;
         tx.set(beacon, w::fields::Light.intensity, 9.0f)
             .set(beacon, w::fields::Light.color, {std::numeric_limits<float>::quiet_NaN(), 0.0f, 0.0f});
         REQUIRE(world.submit(tx).isOk());
       }},
  };
}

[[nodiscard]] std::string transcriptsText() {
  std::string text;
  for (const auto& [name, run] : scenarios()) {
    GameplayFixture f;
    run(f.world);
    json::Value submissions = json::Value::array();
    for (const auto& submission : f.recording.submissions) {
      json::Value commands = json::Value::array();
      for (const access::Command& command : submission.commands) commands.push(codec::encode(command));
      json::Value s = json::Value::object();
      s.set("transaction", json::Value::boolean(submission.transaction));
      s.set("commands", std::move(commands));
      submissions.push(std::move(s));
    }
    json::Value out = json::Value::object();
    out.set("scenario", json::Value::string(name));
    out.set("submissions", std::move(submissions));
    text += json::write(out) + "\n";
  }
  return text;
}

}  // namespace

TEST_CASE("codec_vectors.jsonl is what the C++ codec writes now", "[csharp][conformance]") {
  checkCurrent(codecVectorsText(), "codec_vectors.jsonl");
}

TEST_CASE("sdk_transcripts.jsonl is what the C++ Gameplay SDK submits now", "[csharp][conformance]") {
  checkCurrent(transcriptsText(), "sdk_transcripts.jsonl");
}

TEST_CASE("the vectors are deterministic and LF-only", "[csharp][conformance]") {
  const std::string a = codecVectorsText();
  CHECK(codecVectorsText() == a);
  CHECK(a.find('\r') == std::string::npos);
  const std::string t = transcriptsText();
  CHECK(transcriptsText() == t);
  CHECK(t.find('\r') == std::string::npos);
}
